version: '3.6'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    build: ./compose/postgres
    env_file:
      - .env.local
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups

  redis:
    build: ./compose/redis

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
